language: php

sudo: false

php:
- "7.1"
- "7.2"

cache:
  directories:
  - $HOME/.composer/cache

install: composer install

script:
- vendor/bin/phpunit

after_script:
- travis_retry php vendor/bin/php-coveralls -v
